### ISSUE TITLE
Prevent Output panel to automatically pop up for every issue

### ISSUE THREAD

**Issue by finferflu** [mauve/vscode-terraform#115]
Hi,

Right now whenever I'm trying to create a local variable in Terraform the Output panel pops up multiple times. I have `"debug.internalConsoleOptions": "neverOpen"` set in my VS Code configuration, but it doesn't seem to help at all. My understanding is that this behaviour is controlled by the extension, so could you please advise on how to fix that?

Thank you.

**Comment by mauve** [comment]
This behavior is indeed controlled by the extension. I will disable this behavior I didn't expect it to be this intrusive.

**Comment by finferflu** [comment]
@mauve Thanks a lot for the blazing fast response and for your assistance! Could you please let me know when the fix is released so that I can update my extension?

Thank you!

**Comment by finferflu** [comment]
That was fast! Thanks very much!

**Comment by bionicles** [comment]
still having this issue in 1.4.0 ! where is the fix documented? / how do you make this popup stop? disabling the extension for now :(
