### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by kasunsjc** [mauve/vscode-terraform#118]
I notice when this extension running for intellisense, CPU usage gets higher and take long time to show suggestions

**Comment by mauve** [comment]
Thanks for your bug report. Are there special actions you can narrow it down to which trigger this behavior?

Can you share your templates?

Kind regards, Mikael

**Comment by darko-mesaros** [comment]
I've also experienced the same issue. This is how it manifested itself:
- I was adding a new resource to an existing *.tf file 
- I was about to add the `tags` property to it
- As soon as I typed the first character of the tag key - all keyboard input in VSCode stopped responding. I could still click around - but VSCode completely was not accepting any keyboard input. 

Here is the tf snippet I was editing:
```
user_data = "${data.template_cloudinit_config.cloudinit.rendered}"
tags{
  Name = "tf_instance01"
  managed_by = "terraform"
}
```

The only way I remedied this is by Disabling the plugin - Restarting VSCode - Enabling the plugin. 

I am running this on VSCode version 1.25.1 on Mac OS X Sierra.

**Comment by kasunsjc** [comment]
As @darko-mesaros mentioned when I try to add tags this happens so I need to disable vscode and restart again

**Comment by zachncst** [comment]
I've experienced this as well. Sometimes reindexing is hanging after, have to restart several times. It looks like I have 3 processes in activity monitor (code helper) all hitting the same CPU. Maybe this is a file locking issue? 

Mac OS X 10.13.6 (17G65)

VsCode Version 1.25.1 (1.25.1)
1dfc5e557209371715f655691b1235b6b26a06be
2018-07-11T15:27:07.646Z

**Comment by mauve** [comment]
Thanks for the bug reports, I am working on a fix but it will take a few more days as it seems I need to do some larger changes. Thanks for the patience and the thanks for using my extension.

**Comment by kasunsjc** [comment]
@mauve Thanks I really like this extension hope to see the fix soon !!

**Comment by thefotios-enigma** [comment]
I've noticed the same thing happening in `locals` blocks. As soon as you start typing, it looks like it's firing the parser which hangs (because the statement isn't complete yet. Right after typing 
```
locals {  
  s # hangs right after entering the first char
``` 

This is an error message I got:
> key 's' expected start of object ('{') or assignment ('=')

**Comment by n1te1337** [comment]
@mauve any updates on this issue? I'm having the same problem as @thefotios-enigma:
```
resource "aws_alb_listener" "main" {
  default_action {
    type = "redirect"

    redirect {
      p
    }
  }
}
```
Essentially as soon as I type something into a resource block (ie. here when I try to type "protocol" in the `redirect` block) it hangs on the first character. The moment that happens I can't type anything (or even undo the change), the CPU for the `Code Helper` goes straight to 100% and the fan in my laptop makes a noise like it's about to launch into outer space.

The only solution is to kill the `Code Helper` process but as soon as I type something into the block it does the same thing all over again.

As you may imagine that makes the extension unusable :(

Any help much appreciated.

**Comment by marrik96** [comment]
I'm having similar issue.  CPU does not jump to 100% but goes to ~40%, enough where my laptop fan comes on.

**Comment by Deric4** [comment]
having exact same issue as  @n1te1337 except I'm adding  a `timeout` block to a resource. CPU spikes to 100% . Looks like the plugin isn't handling non key value declarations inside resources?

**Comment by gregburek** [comment]
Same as above, including when at 100% CPU the entire plugin subsystem seems to freeze, meaning my vim controls stopping editing and moving. My attempt to mitigate with config doesn't work it seems:
```
    "[terraform]": {
        "editor.formatOnSave": true,
    },
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 5000,
        "exclude": [
            ".terraform/**/*",
            ".terraform/*",
            "terraform.tfstate.d/*",
            ".mypy_cache/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.codelens.enabled": false,
    "terraform.templateDirectory": "terraform/files",
```

**Comment by michaelmoussa** [comment]
I just started running into this as well. Been using the Terraform plugin and `locals` for a while now, so this must have been introduced in a recent update.

I seem to be able to avoid the spike by adding a label after the `locals` keyword (like one would when declaring a `variable`). Obviously, this is not syntactically valid and will cause Terraform to complain, _but_ it will allow me to fill in the keys+values that I need without killing the editor. Once I've filled in the values I need, I can delete the label and go about my business.

Example below:

![image](https://user-images.githubusercontent.com/183833/45362454-de144580-b5a2-11e8-99fb-a5b993d3b2fb.png)

This seems to be consistent with what [this user](https://github.com/mauve/vscode-terraform/issues/118#issuecomment-411878037) and [this user](https://github.com/mauve/vscode-terraform/issues/118#issuecomment-417909799) are experiencing - instances of a key / keyword followed by `{` will cause a CPU spike and force a restart after the next character is entered inside the curly braces.

Hopefully that will help narrow things down.

**Comment by michaelmoussa** [comment]
I dug a bit deeper and managed to come up with a solution.

The issue was introduced in version `1.3.3` by this block:

https://github.com/mauve/vscode-terraform/blob/e7b830ad42581abe5da08b8b95906580b7ef806c/src/autocompletion/completion-provider.ts#L200-L201

The block was added to address a `completion-provider: Failed to provide completions TypeError: Cannot read property 'args' of undefined` error that was introduced in `1.3.0`; however, it results in an infinite loop because [`argumentsLength`](https://github.com/mauve/vscode-terraform/blob/e7b830ad42581abe5da08b8b95906580b7ef806c/src/autocompletion/completion-provider.ts#L198) doesn't get decremented.

The easiest fix is to change:

```javascript
            if (!field)
              continue;
```

to:

```javascript
            if (!field) {
              argumentsLength--;
              continue;
            }
```

You can fix this yourself while you wait for an updated plugin version by editing `~/.vscode/extensions/mauve.terraform-1.3.4/out/src/autocompletion/completion-provider.js` and modifying the affected line. (**Note:** replace `1.3.4` with whichever version you have installed).

**Comment by marrik96** [comment]
Thank you @michaelmoussa for the temp fix!  I have not been writing much HCL lately but this was kind of a painful bug.

**Comment by kasunsjc** [comment]
Thanks @michaelmoussa !!

**Comment by arush0** [comment]
I'm still having this issue. I made the changes that @michaelmoussa pointed out and they worked for about a day. Are there other places this can be fixed?

**Comment by mauve** [comment]
@arush0 I am not able to reproduce this locally at all, since you are already running a plugin version which you have built locally, next time when you hit this problem can you just break in the debugger and tell me where the stacktrace?

**Comment by mauve** [comment]
@michaelmoussa thanks for your fix, your commit was:

```
              if (!field)
+              argumentsLength--;
                continue;
```

The commit was missing braces which means you hit the continue path unconditionally. In my version I "had to" fix it to be:

```
            if (!field) {
              argumentsLength--;
              continue;
            }
```

As I cannot reproduce this issue locally any help would be much appreciated.

**Comment by mauve** [comment]
Anyway version 1.3.5 is coming today which contains _at least_ the fix from @michaelmoussa. In the meantime you can help by sending my a link to the templates which break this behavior, if you cannot post them publically, you can always email me at mikael.olenfalk@gmail.com

**Comment by arush0** [comment]
My issues were in "aws_iam_policy_document" types, in the "statement {}" sections. But updating to 1.3.5 resolved the issue. Thanks!

**Comment by michaelmoussa** [comment]
Oh wow, thanks for catching that @mauve - sorry for the oversight! I can confirm that your correction _is_ what I meant to submit. I've since upgraded to 1.3.5 and can confirm I'm not seeing the high CPU behavior and freezing any longer.

**Comment by mauve** [comment]
I guess the issues have been solved by the fix made by @michaelmoussa, I will try and add some regression tests around this.

In the meantime I will close this bug. Feel free to open again.

Thanks for using my plugin and thanks for taking the time to open bug reports.

**Comment by joshtharakan** [comment]
I am still facing this issue. 
It happens when I just keep around 6+ tf files in vscode
