### ISSUE TITLE
When terraform.indexing.enabled is true, Code UI freezes on Ubuntu

### ISSUE THREAD

**Issue by pdecat** [mauve/vscode-terraform#53]
Indexing is now enabled by default since vscode-terraform 0.0.21: https://github.com/mauve/vscode-terraform/commit/7d170c693f4e3b4424bcaf19eacf5899075b841e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R149

This change seems to freeze Code UI on my system (Ubuntu 17.10 with code 1.21.0-1520420608) where `terraform-index` is not installed.

Work-around, start Code with `code --disable-extensions` and add `"terraform.indexing.enabled": false` to user settings.

As soon as I change terraform.indexing.enabled from false to true, code UI freezes.

![settings json - objenious - visual studio code_291](https://user-images.githubusercontent.com/318490/37206795-670748ec-239a-11e8-98fe-f6e60fe75b79.png)

Here are some logs when that happens:

```
==> /home/pdecat/.config/Code/logs/20180309T110358/exthost1.log <==                                    
[2018-03-09 13:07:13.692] [exthost1] [info] ExtensionService#_doActivateExtension mauve.terraform {"startup":false,"activationEvent":"onLanguage:terraform"}
[2018-03-09 13:07:13.692] [exthost1] [info] ExtensionService#loadCommonJSModule /home/pdecat/.vscode/extensions/mauve.terraform-0.0.21/out/src/extension
```

```
==> /home/pdecat/.config/Code/logs/20180309T110358/main.log <==                                                                                                                                                
[2018-03-09 13:04:28.563] [main] [info] update#setState checking for updates                           
[2018-03-09 13:04:29.238] [main] [info] update#setState idle                                           
[2018-03-09 13:07:46.637] [main] [error] [VS Code]: detected unresponsive                              
```

Note: only the main view is frozen, menu and developer tools still work.

**Comment by mauve** [comment]
Seems to only be the case on ubuntu (cannot reproduce on mac for example).

@pdecat  is there anything interesting in the `Console` tab of the Developer Tools (`Ctrl-Shift-I`)

**Comment by pdecat** [comment]
Here is what happen in the developer console:

```
[Extension Host] Scanning for all terraform files...
console.ts:136 [Extension Host] Scanning done.
935 console.ts:136 [Extension Host] Could not parse: Error: spawn terraform-index ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by pdecat** [comment]
Hmm, the freeze seems to trigger only when a terraform file is first opened.

**Comment by pdecat** [comment]
When the freeze actually happen, there is only one occurrence of the error message in the console (above there were 935 occurrences and it did not freeze as now terraform file was opened):

```
console.ts:136 [Extension Host] Scanning for all terraform files...
console.ts:136 [Extension Host] Scanning done.
console.ts:136 [Extension Host] Could not parse: Error: spawn terraform-index ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by mauve** [comment]
if you don't have terraform-index installed those errors are expected but the hang is obviously not expected

**Comment by mauve** [comment]
I just pushed 0.0.22 which does not require indexing to be true (so does not enable it by default), please try it.

**Comment by pdecat** [comment]
Upgrading to 0.0.22 and removing `terraform.indexing.enabled` from user settings works fine.

However, the hang still happens when `terraform.indexing.enabled` is set to true.

Also, I installed `terraform-index` and the hang also happens with the following messages in the console:

```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Scanning for all terraform files...
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Scanning done.
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:257 [Extension Host] Updating index for  file:///home/pdecat/workspaces/test/test.tf
```

I have updated the title accordingly.

**Comment by mauve** [comment]
this should be fixed in 1.0.0.

**Comment by nandac** [comment]
I am seeing this same issue in version 1.3.4.
